application:
  port: 8080
  host: 0.0.0.0
  hmac_secret: "super-long-and-secret-random-key-needed-to-verify-message-integrity"
  # Cloudflare Turnstile - test key that always passes (for development)
  turnstile_secret_key: "1x0000000000000000000000000000000AA"
database:
  database_path: "newsletter"
  create_if_missing: false
  journal_mode: "WAL"
  synchronous: "NORMAL"
  busy_timeout: 5
  foreign_keys: true
  auto_vacuum: "INCREMENTAL"
  page_size: 4096
  cache_size: "-10000"
  mmap_size: "268435456"
  temp_store: "DEFAULT"
email_client:
  sender_email: "test@gmail.com"
  base_url: "http://127.0.0.1"
  authorization_token: "my-secret-token"
  timeout_milliseconds: 10000
redis_uri: "redis://127.0.0.1:6379"